version: '3.7'

services:
  react-app:
    container_name: react-app
    build:
      context: ./react-app
      dockerfile: Dockerfile.prod
    ports:
      - '1337:80'
  webapi:
    container_name: webapi
    build:
      context: ./webapi
      dockerfile: Dockerfile.prod
    environment:
      - MESSAGE=SERRVICE 1
    ports:
      - '5000:80'